# .pre-commit-config.yaml
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version. Must be kept in sync with installed version.
    rev: v0.11.8 # Match the version installed via pip
    hooks:
    # Run the formatter.
    -   id: ruff-format
    # Run the linter.
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix] # Auto-fix and fail if fixes are made 