repos:
  # Ruff (formatter + linter from official repo)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Find the latest tag on GitHub.
    rev: v0.4.2 
    hooks:
      - id: ruff
        name: ruff (lint + fix)
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        name: ruff (format)

  # MyPy – strict type-checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        name: mypy (strict)
        pass_filenames: false
        additional_dependencies:
          - "mypy==1.15.0"
          - "pydantic~=2.7.1"
          - "pydantic-settings~=2.2.1"
          - "types-requests"
        args:
          - "--config-file"
          - "mypy.ini"
          - "src"

  # Bandit – security scan
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ["-s", "B101"]

  # Safety – dependency vulnerability scan

  # Spell checking
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args:
          - --skip="*.lock,*.json,*.css,*.js,*.html,*.csv,*.parquet,*.png,*.mmd"
          - --ignore-words-list="nd,uint,tod"

# TODO: Consider adding a Markdown link checker if a suitable pre-commit hook is found.
# Many robust link checkers are full CI actions (e.g., lychee).

  - repo: local
    hooks:
      - id: too-many-files
        name: Too many staged files
        entry: bash -c 'COUNT=$(git diff --cached --name-only | wc -l); if [ "$COUNT" -gt 25 ]; then echo "🛑 Commit blocked — $COUNT files staged (max 25). Split your commit."; exit 1; fi;'
        language: system
        stages: [commit]