# .pre-commit-config.yaml
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version. Must be kept in sync with installed version.
    rev: v0.11.8 # Match the version installed via pip
    hooks:
    # Run the formatter.
    -   id: ruff-format
    # Run the linter.
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix] # Auto-fix and fail if fixes are made

- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      additional_dependencies:
        - flake8-bugbear>=23.9.16
      args:
        - --max-line-length=88
        - --ignore=E203,E501,W503

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0          # keep in sync with pyproject/requirements
    hooks:
      - id: mypy
        name: mypy (strict)
        pass_filenames: false       # run once, let mypy discover files itself
        additional_dependencies:
          # runtime-only extras so CI can run without global stubs
          - "mypy==1.15.0"
          - "pydantic>=1.10"     # plugin runtime
          - "types-requests"     # silence requests import
        args:
          - "--config-file"
          - "mypy.ini" 