# .pre-commit-config.yaml
repos:
  # --------------------------------------------------------------------- #
  # Ruff (formatter + linter) — keep version in sync with requirements     #
  # --------------------------------------------------------------------- #
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.241            # ruff==0.0.241 in requirements-dev.txt
    hooks:
      - id: ruff             # does both linting & formatting
        args: [--fix]

  # --------------------------------------------------------------------- #
  # Flake8 — extra opinionated linting (Ruff already covers most rules)    #
  # --------------------------------------------------------------------- #
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==23.9.16 # Pinning exact version
        args:
          - --max-line-length=88
          - --ignore=E203,E501,W503

  # --------------------------------------------------------------------- #
  # MyPy strict static type-checking                                        #
  # --------------------------------------------------------------------- #
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0                 # keep in sync with requirements-dev.txt
    hooks:
      - id: mypy
        name: mypy (strict)
        pass_filenames: false     # run once; MyPy discovers files itself
        additional_dependencies:
          - "mypy==1.15.0"
          - "pydantic~=2.7.1"
          - "pydantic-settings~=2.2.1"
          - "types-requests"      # silence requests import
        args:
          - "--config-file"
          - "mypy.ini"
          - "src"
 