repos:
  # Local Ruff (formatter + linter)
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --fix
        language: python
        types: [python]

  # Black – code formatter
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black

  # isort – import sorter
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  # Flake8 – extra linting
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==23.9.16
        args:
          - --max-line-length=88
          - --ignore=E203,W503

  # MyPy – strict type-checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        name: mypy (strict)
        pass_filenames: false
        additional_dependencies:
          - "mypy==1.15.0"
          - "pydantic~=2.7.1"
          - "pydantic-settings~=2.2.1"
          - "types-requests"
        args:
          - "--config-file"
          - "mypy.ini"
          - "src"

  # Bandit – security scan
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ["-r", ".", "-s", "B101"]

  # Safety – dependency vulnerability scan

  # Spell checking
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args:
          - --skip="*.lock,*.json,*.css,*.js,*.html,*.csv,*.parquet,*.png,*.mmd"
          - --ignore-words-list="nd,uint,tod"

# TODO: Consider adding a Markdown link checker if a suitable pre-commit hook is found.
# Many robust link checkers are full CI actions (e.g., lychee).