line-length = 88
target-version = "py310"

[lint]
select = ["E", "W", "F", "I", "RUF"]
ignore = ["E501"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint.isort]
# We'll keep this section minimal for now
# combine-as-imports = true 