name: Agent headless smoke-test

'on':
  pull_request:

jobs:
  agent-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12" # Pin to 3.12 for better pandas compatibility

      - name: Install project requirements
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Bootstrap & dry-run plan (Option A - run inside container)
        # This step assumes your project has a Dockerfile and pytest is set up to run tests.
        # It will build the Docker image (if prefer_docker is true or on CI)
        # then run the agent's plan, and finally try to run pytest inside the container.
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CI: "true"
          PREFER_DOCKER: "true" # Ensures Docker build is attempted on CI
        run: |
          if [ -f bootstrap_agent.py ]; then
            python bootstrap_agent.py
          else
            echo "bootstrap_agent.py not found, skipping bootstrap step"
          fi
          if [ -f agent_main.py ]; then
            python agent_main.py --plan
          else
            echo "agent_main.py not found, skipping agent plan step"
          fi
          # Run the full test-suite inside the freshly built container. Mount the
          # workspace so that the ``tests`` package is visible inside the container.
          # Running as ``root`` avoids permission issues with volume mounts.
          docker run --rm -u root -v "$PWD":/app -w /app agent_test pytest -q 