name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"] # Test across supported versions

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: requirements-lock.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-lock.txt

    - name: Lint with Ruff (optional, good practice)
      run: |
        pip install ruff
        ruff check .
        ruff format --check .

    - name: Test with pytest
      env:
        RAPIDAPI_KEY: "dummy_key_for_ci"
        CM_API_KEY: ""
        ETHERSCAN_API_KEY: ""
      run: |
        pytest -q

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: ${{ github.repository }}
        fail_ci_if_error: true 