name: Lint

on:
  pull_request:

jobs:
  flake8_lint:
    name: Flake8 Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Flake8
        run: pip install flake8 flake8-bugbear==23.9.16 # Match pre-commit's flake8-bugbear version
      - name: Run Flake8
        run: flake8 . --max-line-length=88 --ignore=E203,W503,E501 