name: Python CI Full Matrix Nightly

on:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: nightly-full-matrix
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.12']
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements-lock.txt') }}
          restore-keys: pip-${{ runner.os }}-
      - name: Cache pip wheels
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip/wheels
          key: wheels-${{ runner.os }}-${{ hashFiles('requirements-lock.txt') }}
          restore-keys: wheels-${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run tests in parallel
        run: pytest -q -n auto 