name: Python CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'docs/**'
      - 'roadmap.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'docs/**'
      - 'roadmap.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      RAPIDAPI_KEY: dummy
      ETHERSCAN_API_KEY: dummy

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements-lock.txt') }}
          restore-keys: pip-${{ runner.os }}-

      - name: Cache pip wheels
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip/wheels
          key: wheels-${{ runner.os }}-${{ hashFiles('requirements-lock.txt') }}
          restore-keys: wheels-${{ runner.os }}-

      - name: Cache virtualenv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('requirements-lock.txt') }}
          restore-keys: venv-${{ runner.os }}-

      - name: Set up virtualenv & install deps (only on cache miss)
        run: |
          if [ ! -d ".venv" ]; then
            python -m venv .venv
            . .venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements-dev.txt
          fi

      - name: Run tests in parallel
        run: .venv/bin/pytest -q -n auto